name: Update

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout macports fork
        uses: actions/checkout@v3
        with:
          repository: jreleaser/macports-ports
          path: macports-ports
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Refresh fork
        run: |
          cd macports-ports
          git remote add upstream https://github.com/macports/macports-ports.git
          git pull upstream master

      - name: Branch update
        run: |
          BRANCH=jreleaser-${{ github.ref_name }}
          cd macports-ports   
          git checkout -b $BRANCH
          cp ../main/ports/devel/jreleaser/Portfile devel/jreleaser/Portfile
          git config --global user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config --global user.name "${{ secrets.AUTHOR_NAME }}"
          git commit -a -m "jreleaser: update to version ${{ github.ref_name }}"
          git push origin $BRANCH
