name: Update

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Checkout macports fork
        uses: actions/checkout@v2
        with:
          repository: aalmiray/macports-ports
          path: macports-ports

      - name: Refresh fork
        run: |
          cd ${GITHUB_WORKSPACE}/macports-ports
          git remote add upstream https://github.com/macports/macports-ports.git
          git pull upstream master

      - name: Grab the tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Branch update
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          BRANCH=jreleaser-${{ steps.vars.outputs.tag }}
          cd ${GITHUB_WORKSPACE}/macports-ports   
          git checkout -b $BRANCH
          cp ${GITHUB_WORKSPACE}/main/ports/devel/jreleaser/Portfile devel/jreleaser/Portfile
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git commit -a -m "Update JReleaser ${{ steps.vars.outputs.tag }}"
          git push origin $BRANCH